#! /usr/bin/env python
"""
Print the map from HDD slots (as seen on the chassis) to Linux device names.

This is only valid for Sun/Oracle X4540 ("Thor") boxes; it might yeild incorrect
results for the older Sun/Oracle X4500 ("Thumper") boxes.
"""

import os
import subprocess
import sys


if 'check_output' in dir(subprocess):
    from subprocess import check_output
else:
    # compatibility with Python < 2.7
    def check_output(*popenargs, **kwargs):
        if 'stdout' in kwargs:
            raise ValueError('stdout argument not allowed, it will be overridden.')
        process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
        output, unused_err = process.communicate()
        retcode = process.poll()
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
            raise subprocess.CalledProcessError(retcode, cmd, output=output)
        return output


## map (controller, disk) to Linux device name
ctl_and_diskno_to_devname_src = ('{'
                         + check_output("""
for disk in /sys/class/scsi_disk/*; do
  aux=$(basename $disk);
  ctl=$(echo $aux | cut -d: -f1);
  devno=$(echo $aux | cut -d: -f3);
  devname=$(basename $disk/device/block/*);
  echo "($ctl, $devno):'$devname',";
done
                         """, shell=True)
                         + '}')
ctl_and_diskno_to_devname = eval(ctl_and_diskno_to_devname_src)

## this was gotten from the `lustre*` machines
sun_x4540_slot_to_ctl_and_diskno = {
#SLOT  CONTROLLER DISK NO.
    0 :  (0      ,   0),
    1 :  (0      ,   1),
    2 :  (0      ,   2),
    3 :  (0      ,   3),
    4 :  (0      ,   4),
    5 :  (0      ,   5),
    6 :  (0      ,   6),
    7 :  (0      ,   7),
    8 :  (1      ,   0),
    9 :  (1      ,   1),
    10:  (1      ,   2),
    11:  (1      ,   3),
    12:  (1      ,   4),
    13:  (1      ,   5),
    14:  (1      ,   6),
    15:  (1      ,   7),
    16:  (2      ,   0),
    17:  (2      ,   1),
    18:  (2      ,   2),
    19:  (2      ,   3),
    20:  (2      ,   4),
    21:  (2      ,   5),
    22:  (2      ,   6),
    23:  (2      ,   7),
    24:  (3      ,   0),
    25:  (3      ,   1),
    26:  (3      ,   2),
    27:  (3      ,   3),
    28:  (3      ,   4),
    29:  (3      ,   5),
    30:  (3      ,   6),
    31:  (3      ,   7),
    32:  (4      ,   0),
    33:  (4      ,   1),
    34:  (4      ,   2),
    35:  (4      ,   3),
    36:  (4      ,   4),
    37:  (4      ,   5),
    38:  (4      ,   6),
    39:  (4      ,   7),
    40:  (5      ,   0),
    41:  (5      ,   1),
    42:  (5      ,   2),
    43:  (5      ,   3),
    44:  (5      ,   4),
    45:  (5      ,   5),
    46:  (5      ,   6),
    47:  (5      ,   7),
}

## pretty-print
for slot, hw in sun_x4540_slot_to_ctl_and_diskno.items():
    try:
        print "%2d: %-s" % (slot, ctl_and_diskno_to_devname[hw])
    except KeyError:
        print "%2d: UNKNOWN" % (slot,)
